openapi: 3.0.0
info:
  title: Event Service API
  version: 1.0.0
  description: API pour gérer les événements dans le système de billetterie
paths:
  /api/events:
    post:
      summary: Créer un événement (event_creator ou admin)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                date: { type: string, format: date-time }
                max_tickets: { type: integer }
      responses:
        '201': { description: Événement créé }
        '400': { description: Champs invalides }
        '401': { description: Non authentifié }
        '403': { description: Non autorisé }
    get:
      summary: Lister tous les événements
      responses:
        '200': { description: Liste des événements }
  /api/events/{id}:
    get:
      summary: Récupérer un événement
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200': { description: Événement trouvé }
        '404': { description: Événement non trouvé }
    put:
      summary: Mettre à jour un événement (event_creator ou admin)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                date: { type: string, format: date-time }
                max_tickets: { type: integer }
      responses:
        '200': { description: Événement mis à jour }
        '404': { description: Événement non trouvé }
        '401': { description: Non authentifié }
        '403': { description: Non autorisé }
    delete:
      summary: Supprimer un événement (event_creator ou admin)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '204': { description: Suppression réussie }
        '404': { description: Événement non trouvé }
        '401': { description: Non authentifié }
        '403': { description: Non autorisé }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT