version: '3.8'
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - event-service
      - auth-service
      - user-service
      - ticket-service
    environment:
      - PORT=3000
    networks:
      - ticketing-network

  event-service:
    build:
      context: ./event-service
      dockerfile: Dockerfile
    ports:
      - "3002:3001"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=ticketing
      - DB_PORT=3306
      - PORT=3001
    volumes:
      - ./event-service/swagger.yaml:/app/swagger.yaml
    networks:
      - ticketing-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3003:3002"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=ticketing
      - DB_PORT=3306
      - PORT=3002
      - JWT_SECRET=microservices
    volumes:
      - ./auth-service/swagger.yaml:/app/swagger.yaml
    networks:
      - ticketing-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3004:3003"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=ticketing
      - DB_PORT=3306
      - PORT=3003
      - JWT_SECRET=microservices
    volumes:
      - ./user-service/swagger.yaml:/app/swagger.yaml
    networks:
      - ticketing-network

  ticket-service:
    build:
      context: ./ticket-service
      dockerfile: Dockerfile
    ports:
      - "3005:3004"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=ticketing
      - DB_PORT=3306
      - PORT=3004
      - JWT_SECRET=microservices
      - RABBITMQ_URL=amqp://rabbitmq:5672
    volumes:
      - ./ticket-service/swagger.yaml:/app/swagger.yaml
    networks:
      - ticketing-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ticketing
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ticketing-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 5s
      retries: 10
      interval: 5s

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Port AMQP
      - "15672:15672"  # Port de gestion (UI)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ticketing-network

  nginx:
    image: nginx:latest
    ports:
      - "9090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-gateway
    networks:
      - ticketing-network

networks:
  ticketing-network:
    driver: bridge

volumes:
  mysql-data:
  rabbitmq-data: