openapi: 3.0.0
info:
  title: Ticket Service API
  version: 1.0.0
  description: API pour gérer l’achat et la récupération des billets
paths:
  /api/tickets/purchase:
    post:
      summary: Acheter un billet
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eventId: { type: integer }
      responses:
        '201': { description: Billet créé }
        '400': { description: Champs manquants ou erreur d’achat }
        '401': { description: Non authentifié }
  /api/tickets/my-tickets:
    get:
      summary: Récupérer les billets de l’utilisateur
      security:
        - bearerAuth: []
      responses:
        '200': { description: Liste des billets }
        '401': { description: Non authentifié }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT